apiVersion: openliberty.io/v1beta1
# tag::kind[]
kind: OpenLibertyApplication
# end::kind[]

metadata:
  name: inventory-deployment
spec:
  # tag::applicationImage[]
  applicationImage: liberty-deepdive-inventory:1.0-SNAPSHOT
  # end::applicationImage[]
  selector:
    matchLabels:
      app: inventory
  # tag::replicas[]
  replicas: 3
  # end::replicas[]
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        image: liberty-deepdive-inventory:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000