apiVersion: apps.openliberty.io/v1beta2
# tag::kind[]
kind: OpenLibertyApplication
# end::kind[]
metadata:
  name: inventory-deployment
  labels:
    name: inventory-deployment
spec:
  # tag::applicationImage[]
  applicationImage: liberty-deepdive-inventory:1.0-SNAPSHOT
  # end::applicationImage[]
  service:
    port: 9080
    targetPort: 9080
    nodePort: 30008
  env:
    - name: CONTEXT_ROOT
      valueFrom:
        configMapKeyRef:
          name: sys-app-root
          key: contextRoot
---
apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  # tag::applicationImage[]
  applicationImage: postgres:14.1
  # end::applicationImage[]
  service:
    port: 5432
    targetPort: 5432
    nodePort: 30008
  env:
    - name: SYSTEM_APP_USERNAME
      valueFrom:
        secretKeyRef:
          name: sys-app-credentials
          key: username
    - name: SYSTEM_APP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sys-app-credentials
          key: password