apiVersion: apps.openliberty.io/v1
# tag::kind[]
kind: OpenLibertyApplication
# end::kind[]
metadata:
  name: inventory-deployment
  labels:
    name: inventory-deployment
spec:
  # tag::applicationImage[]
  applicationImage: liberty-deepdive-inventory:1.0-SNAPSHOT
  # end::applicationImage[]
  service:
    port: 9453
  env:
    - name: POSTGRES_HOSTNAME
      value: "postgres"
