apiVersion: apps.openliberty.io/v1beta2
# tag::kind[]
kind: OpenLibertyApplication
# end::kind[]
metadata:
  name: inventory-deployment
  labels:
    name: inventory-deployment
spec:
  # tag::applicationImage[]
  applicationImage: liberty-deepdive-inventory:1.0-SNAPSHOT
  # end::applicationImage[]
  service:
    port: 9080
  volumeMounts:
  - name: postgres
   # tag::mountPath[]
    mountPath: "/config/variables/postgres"
    # end::mountPath[]
    readOnly: true
  volumes:
  - name: postgres
    secret:
      secretName: post-app-credentials 
  env:
    - name: CONTEXT_ROOT
      valueFrom:
        configMapKeyRef:
          name: inv-app-root
          key: contextRoot
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    name: inventory-deployment
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    # tag::port[]
    nodePort: 30000
    # end::port[]

